# Task 1.1: First principles output

In [2]:
import pandas as pd
import numpy as np

In [3]:
'''#Intro to Neural Network Modeling 
# Python Neural Network Model of Spray Cooling Test System

>>>>> start CodeP2.1F23
    V.P. Carey, ME249, Fall 2023'''

# version 3 print function
from __future__ import print_function

# import math, numpy and other usefuk packages
import math
import numpy 

%matplotlib inline
# importing the required module 
import matplotlib.pyplot as plt 
plt.rcParams['figure.figsize'] = [10, 8] # for square canvas


#assembling data array
#store array where rows are data vectors [x01, x02, x03, y3]
xydata = []

xydata = [[20./20.2, 13.0/14.5, 310.8/308.0, 30.99/32.4], [20./20.2, 14.5/14.5, 308.0/308.0, 32.2/32.4]]
xydata.append([20./20.2, 15.3/14.5, 306.0/308.0, 31.7/32.4])
xydata.append([20.2/20.2, 13.0/14.5, 310.8/308.0, 30.92/32.4]) 
xydata.append([20./20.2, 14.5/14.5, 308.0/308.0, 32.4/32.4]) 
xydata.append([20./20.2, 15.3/14.5, 306.0/308.0, 31.4/32.4]) 
xydata.append([24./20.2, 13.0/14.5, 310.8/308.0, 35.53/32.4]) 
xydata.append([36./20.2, 14.5/14.5, 308.0/308.0, 46.4/32.4]) 
print (xydata)

[[0.9900990099009901, 0.896551724137931, 1.009090909090909, 0.9564814814814815], [0.9900990099009901, 1.0, 1.0, 0.9938271604938272], [0.9900990099009901, 1.0551724137931036, 0.9935064935064936, 0.9783950617283951], [1.0, 0.896551724137931, 1.009090909090909, 0.954320987654321], [0.9900990099009901, 1.0, 1.0, 1.0], [0.9900990099009901, 1.0551724137931036, 0.9935064935064936, 0.9691358024691358], [1.188118811881188, 0.896551724137931, 1.009090909090909, 1.096604938271605], [1.7821782178217822, 1.0, 1.0, 1.4320987654320987]]

In [4]:
#set starting values 
w01n =  1.23 
w02n =  0.40 
w03n =  0.70
b1n =  -0.15
w12n =  0.72
b2n =  -0.12
w23n =  0.7
b3n =  0.01

#start of batch loop  

for k in range (0,200):
    icount = 0
    #initialize error and derivative parameters
    E3ti = 0.
    dE3da3 = 0.
    dE3dw01ti = 0.
    dE3dw02ti = 0.
    dE3dw03ti = 0.
    dE3db1ti = 0.
    dE3dw12ti = 0.
    dE3db2ti = 0.
    dE3dw23ti = 0.
    dE3db3ti = 0.
 
    w01 = w01n 
    w02 = w02n
    w03 = w03n
    b1 = b1n 
    w12 = w12n
    b2 = b2n 
    w23 = w23n 
    b3 = b3n 
    
    #doing calcuations for each data point 
    for i in range(0,8):
        #compute activation functions and their derivatives
        z1 = w01*xydata[i][0]+w02*xydata[i][1]+w03*xydata[i][2]+b1 
        sig1 = z1
        sigp1 = 1.0
        if z1 < 0.0:
            sig1 = math.exp(z1) - 1.0
            sigp1 = math.exp(z1)
        a1 = sig1

        z2 = w12*a1+b2 
        sig2 = z2
        sigp2 = 1.0
        if z2 < 0.0:
            sig2 = math.exp(z2) - 1.0
            sigp2 = math.exp(z2)
        a2 = sig2

        z3 = w23*a2+b3 
        sig3 = z3
        sigp3 = 1.0
        if z3 < 0.0:
            sig3 = math.exp(z3) - 1.0
            sigp3 = math.exp(z3)
        a3 = sig3
        
        
        #compute derivatives for backpropagation
        #add to sum for batch average calculation
        E3ti = E3ti +(a3 - xydata[i][3])*(a3 - xydata[i][3])
        dE3da3 = 2.*(a3 - xydata[i][3])
        
        dE3dw01ti = dE3dw01ti + dE3da3*sigp3*w23*sigp2*w12*sigp1*xydata[i][0]
        dE3dw02ti = dE3dw02ti + dE3da3*sigp3*w23*sigp2*w12*sigp1*xydata[i][1]

        #Write out these derivatives
        dE3dw03ti = dE3dw02ti * sigp3 * w23 * sigp2 * w12 * sigp1 * xydata[i][2]
        dE3db1ti = dE3dw02ti * sigp3 * w23 * sigp2 * w12 * sigp1 
        
        dE3dw12ti = dE3dw02ti * sigp3 * w23 * sigp2 * a1
        dE3db2ti = dE3dw02ti * sigp3 * w23 * sigp2
        
        dE3dw23ti = dE3dw02ti * sigp3 * a2
        dE3db3ti = dE3dw02ti * sigp3
        
        icount = i + 1
        # end  calculations for each data point in batch
        
    #compute batch averaged values
    E3 = E3ti/icount
    dE3dw01 = dE3dw01ti/icount
    dE3dw02 = dE3dw02ti/icount
    dE3dw03 = dE3dw03ti/icount
    dE3db1 = dE3db1ti/icount
    dE3dw12 = dE3dw12ti/icount
    dE3db2 = dE3db2ti/icount
    dE3dw23 = dE3dw23ti/icount
    dE3db3 = dE3db3ti/icount
    
    #set gam = learning rate
    gam = 0.03
    if E3 < 0.07: 
        gam = 0.009

    w01n = w01 + gam*(-E3)/dE3dw01
    w02n = w02 + gam*(-E3)/dE3dw02
    w03n = w03 + gam*(-E3)/dE3dw03
    b1n = b1 + gam*(-E3)/dE3db1
    w12n = w12 + gam*(-E3)/dE3dw12
    b2n = b2 + gam*(-E3)/dE3db2
    
    w23n = w23 + gam*(-E3)/dE3dw23
    b3n = b3 + gam*(-E3)/dE3db3
    
    #printing for each iteration
    # print ('last w01, w02, w03, w12, w23:')
    # print ('last b1, b2, b3:')
    # print (w01, w02, w03, w12, w23)
    # print (b1, b2, b3)
    # print ('E3 = ', E3, 'icount =', icount)
    # print ('next ws:', w01n, w02n, w03n, w12n, w23n)
    # print ('next bs:', b1n, b2n, b3n)
    
    #quit if squared error is below target
    if E3 < 0.00035:
        break
    

print ('last w01, w02, w03, w12, w23:')
print (w01, w02, w03, w12, w23)

print ('last b1, b2, b3:')
print (b1, b2, b3)
#decomment print statements below if you want to print neuron outputs
#print ('z1 =', z1)
#print ('a1 =', a1)
#print ('z2 =', z2)
#print ('a2 =', a2)
#print ('z3 =', z3)
#print ('a3 =', a3)

#print comparison of data and trained network predictions
# restore raw data values  
xydatar = [[20., 13.0, 310.8, 30.97], [20., 14.5, 308.0, 32.3]]
xydatar.append([20., 15.3, 306.0, 31.5])
xydatar.append([20.2, 13.0, 310.8, 30.91]) 
xydatar.append([20., 14.5, 308.0, 32.5]) 
xydatar.append([20., 15.3, 306.0, 31.4]) 
xydatar.append([24., 13.0, 310.8, 35.59]) 
xydatar.append([36., 14.5, 308.0, 46.4])
print ('Tdbin, Twbin, qdot, Tdbout, ypredicted:')

predicted_values = []

for i in range(0,8): 
    z1 = w01*xydata[i][0]+w02*xydata[i][1]+w03*xydata[i][2]+b1 
    sig1 = z1
    sigp1 = 1.0
    if z1 < 0.0:
        sig1 = math.exp(z1) - 1.0
        sigp1 = math.exp(z1)
    a1 = sig1

    z2 = w12*a1+b2 
    sig2 = z2
    sigp2 = 1.0
    if z2 < 0.0:
        sig2 = math.exp(z2) - 1.0
        sigp2 = math.exp(z2)
    a2 = sig2

    z3 = w23*a2+b3 
    sig3 = z3
    sigp3 = 1.0
    if z3 < 0.0:
        sig3 = math.exp(z3) - 1.0
        sigp3 = math.exp(z3)
    a3 = sig3
    predicted_values.append(a3 * 32.4)
    print (xydatar[i][0], xydatar[i][1], xydatar[i][2], xydatar[i][3], a3*32.4)

rms = E3 ** 0.5
print ('E3 = ', E3, 'icount =', icount)
print(f"RMS = {rms}")

last w01, w02, w03, w12, w23:
1.2252671508985415 0.3940557501299764 0.6881628364805767 0.7172767821733249 0.697197942292706
last b1, b2, b3:
-0.16183716351942315 -0.12850768512517474 0.004055750129976315
Tdbin, Twbin, qdot, Tdbout, ypredicted:
20.0 13.0 310.8 30.97 31.238167853045418
20.0 14.5 308.0 32.3 31.79729712234356
20.0 15.3 306.0 31.5 32.07715722939482
20.2 13.0 310.8 30.91 31.43472882756245
20.0 14.5 308.0 32.5 31.79729712234356
20.0 15.3 306.0 31.4 32.07715722939482
24.0 13.0 310.8 35.59 35.16938734338613
36.0 14.5 308.0 46.4 47.52217508370643
E3 =  0.00033841798497099564 icount = 8
RMS = 0.018396140491173565

In [5]:
predicted_values

[31.238167853045418,
 31.79729712234356,
 32.07715722939482,
 31.43472882756245,
 31.79729712234356,
 32.07715722939482,
 35.16938734338613,
 47.52217508370643]

Task 1.2

## 1(d)

In [6]:
xydatar

[[20.0, 13.0, 310.8, 30.97],
 [20.0, 14.5, 308.0, 32.3],
 [20.0, 15.3, 306.0, 31.5],
 [20.2, 13.0, 310.8, 30.91],
 [20.0, 14.5, 308.0, 32.5],
 [20.0, 15.3, 306.0, 31.4],
 [24.0, 13.0, 310.8, 35.59],
 [36.0, 14.5, 308.0, 46.4]]

In [7]:
xydatar_df = pd.DataFrame(xydatar, columns=["x01", "x02", "x03", "y3"])
xydatar_df

    x01   x02    x03     y3
0  20.0  13.0  310.8  30.97
1  20.0  14.5  308.0  32.30
2  20.0  15.3  306.0  31.50
3  20.2  13.0  310.8  30.91
4  20.0  14.5  308.0  32.50
5  20.0  15.3  306.0  31.40
6  24.0  13.0  310.8  35.59
7  36.0  14.5  308.0  46.40

In [8]:
xydatar_df["y3"].values

array([30.97, 32.3 , 31.5 , 30.91, 32.5 , 31.4 , 35.59, 46.4 ])

### New training data:

In [9]:
xydatar

[[20.0, 13.0, 310.8, 30.97],
 [20.0, 14.5, 308.0, 32.3],
 [20.0, 15.3, 306.0, 31.5],
 [20.2, 13.0, 310.8, 30.91],
 [20.0, 14.5, 308.0, 32.5],
 [20.0, 15.3, 306.0, 31.4],
 [24.0, 13.0, 310.8, 35.59],
 [36.0, 14.5, 308.0, 46.4]]

In [10]:
xydatar_new_df = xydatar_df.multiply(1.2)
xydatar_new_df = xydatar_new_df.divide([20.2, 14.5, 308.0, 32.4])
xydatar_new_df

        x01       x02       x03        y3
0  1.188119  1.075862  1.210909  1.147037
1  1.188119  1.200000  1.200000  1.196296
2  1.188119  1.266207  1.192208  1.166667
3  1.200000  1.075862  1.210909  1.144815
4  1.188119  1.200000  1.200000  1.203704
5  1.188119  1.266207  1.192208  1.162963
6  1.425743  1.075862  1.210909  1.318148
7  2.138614  1.200000  1.200000  1.718519

In [11]:
xydatar_new_df.values

array([[1.18811881, 1.07586207, 1.21090909, 1.14703704],
       [1.18811881, 1.2       , 1.2       , 1.1962963 ],
       [1.18811881, 1.2662069 , 1.19220779, 1.16666667],
       [1.2       , 1.07586207, 1.21090909, 1.14481481],
       [1.18811881, 1.2       , 1.2       , 1.2037037 ],
       [1.18811881, 1.2662069 , 1.19220779, 1.16296296],
       [1.42574257, 1.07586207, 1.21090909, 1.31814815],
       [2.13861386, 1.2       , 1.2       , 1.71851852]])

### Training model on new data

In [12]:
xydata = xydatar_new_df.values.tolist()
xydata

[[1.188118811881188,
  1.0758620689655172,
  1.210909090909091,
  1.1470370370370369],
 [1.188118811881188, 1.2, 1.2, 1.1962962962962962],
 [1.188118811881188,
  1.2662068965517241,
  1.1922077922077923,
  1.1666666666666667],
 [1.2, 1.0758620689655172, 1.210909090909091, 1.1448148148148147],
 [1.188118811881188, 1.2, 1.2, 1.2037037037037037],
 [1.188118811881188,
  1.2662068965517241,
  1.1922077922077923,
  1.162962962962963],
 [1.4257425742574257,
  1.0758620689655172,
  1.210909090909091,
  1.3181481481481483],
 [2.1386138613861383, 1.2, 1.2, 1.7185185185185186]]

In [13]:
#set starting values 
w01n =  1.23 
w02n =  0.40 
w03n =  0.70
b1n =  -0.15
w12n =  0.72
b2n =  -0.12
w23n =  0.7
b3n =  0.01

#start of batch loop  

for k in range (0,200):
    icount = 0
    #initialize error and derivative parameters
    E3ti = 0.
    dE3da3 = 0.
    dE3dw01ti = 0.
    dE3dw02ti = 0.
    dE3dw03ti = 0.
    dE3db1ti = 0.
    dE3dw12ti = 0.
    dE3db2ti = 0.
    dE3dw23ti = 0.
    dE3db3ti = 0.
 
    w01 = w01n 
    w02 = w02n
    w03 = w03n
    b1 = b1n 
    w12 = w12n
    b2 = b2n 
    w23 = w23n 
    b3 = b3n 
    
    #doing calcuations for each data point 
    for i in range(0,8):
        #compute activation functions and their derivatives
        z1 = w01*xydata[i][0]+w02*xydata[i][1]+w03*xydata[i][2]+b1 
        sig1 = z1
        sigp1 = 1.0
        if z1 < 0.0:
            sig1 = math.exp(z1) - 1.0
            sigp1 = math.exp(z1)
        a1 = sig1

        z2 = w12*a1+b2 
        sig2 = z2
        sigp2 = 1.0
        if z2 < 0.0:
            sig2 = math.exp(z2) - 1.0
            sigp2 = math.exp(z2)
        a2 = sig2

        z3 = w23*a2+b3 
        sig3 = z3
        sigp3 = 1.0
        if z3 < 0.0:
            sig3 = math.exp(z3) - 1.0
            sigp3 = math.exp(z3)
        a3 = sig3
        
        
        #compute derivatives for backpropagation
        #add to sum for batch average calculation
        E3ti = E3ti +(a3 - xydata[i][3])*(a3 - xydata[i][3])
        dE3da3 = 2.*(a3 - xydata[i][3])
        
        dE3dw01ti = dE3dw01ti + dE3da3*sigp3*w23*sigp2*w12*sigp1*xydata[i][0]
        dE3dw02ti = dE3dw02ti + dE3da3*sigp3*w23*sigp2*w12*sigp1*xydata[i][1]

        #Write out these derivatives
        dE3dw03ti = dE3dw02ti * sigp3 * w23 * sigp2 * w12 * sigp1 * xydata[i][2]
        dE3db1ti = dE3dw02ti * sigp3 * w23 * sigp2 * w12 * sigp1 
        
        dE3dw12ti = dE3dw02ti * sigp3 * w23 * sigp2 * a1
        dE3db2ti = dE3dw02ti * sigp3 * w23 * sigp2
        
        dE3dw23ti = dE3dw02ti * sigp3 * a2
        dE3db3ti = dE3dw02ti * sigp3
        
        icount = i + 1
        # end  calculations for each data point in batch
        
    #compute batch averaged values
    E3 = E3ti/icount
    dE3dw01 = dE3dw01ti/icount
    dE3dw02 = dE3dw02ti/icount
    dE3dw03 = dE3dw03ti/icount
    dE3db1 = dE3db1ti/icount
    dE3dw12 = dE3dw12ti/icount
    dE3db2 = dE3db2ti/icount
    dE3dw23 = dE3dw23ti/icount
    dE3db3 = dE3db3ti/icount
    
    #set gam = learning rate
    gam = 0.03
    if E3 < 0.07: 
        gam = 0.009

    w01n = w01 + gam*(-E3)/dE3dw01
    w02n = w02 + gam*(-E3)/dE3dw02
    w03n = w03 + gam*(-E3)/dE3dw03
    b1n = b1 + gam*(-E3)/dE3db1
    w12n = w12 + gam*(-E3)/dE3dw12
    b2n = b2 + gam*(-E3)/dE3db2
    
    w23n = w23 + gam*(-E3)/dE3dw23
    b3n = b3 + gam*(-E3)/dE3db3
    
    #printing for each iteration
    # print ('last w01, w02, w03, w12, w23:')
    # print ('last b1, b2, b3:')
    # print (w01, w02, w03, w12, w23)
    # print (b1, b2, b3)
    # print ('E3 = ', E3, 'icount =', icount)
    # print ('next ws:', w01n, w02n, w03n, w12n, w23n)
    # print ('next bs:', b1n, b2n, b3n)
    
    #quit if squared error is below target
    if E3 < 0.00035:
        break
    

print ('last w01, w02, w03, w12, w23:')
print (w01, w02, w03, w12, w23)

print ('last b1, b2, b3:')
print (b1, b2, b3)
#decomment print statements below if you want to print neuron outputs
#print ('z1 =', z1)
#print ('a1 =', a1)
#print ('z2 =', z2)
#print ('a2 =', a2)
#print ('z3 =', z3)
#print ('a3 =', a3)
predicted_values = []
for i in range(0,8): 
    z1 = w01*xydata[i][0]+w02*xydata[i][1]+w03*xydata[i][2]+b1 
    sig1 = z1
    sigp1 = 1.0
    if z1 < 0.0:
        sig1 = math.exp(z1) - 1.0
        sigp1 = math.exp(z1)
    a1 = sig1

    z2 = w12*a1+b2 
    sig2 = z2
    sigp2 = 1.0
    if z2 < 0.0:
        sig2 = math.exp(z2) - 1.0
        sigp2 = math.exp(z2)
    a2 = sig2

    z3 = w23*a2+b3 
    sig3 = z3
    sigp3 = 1.0
    if z3 < 0.0:
        sig3 = math.exp(z3) - 1.0
        sigp3 = math.exp(z3)
    a3 = sig3

    predicted_values.append(a3 * 32.4)
    print (xydatar[i][0], xydatar[i][1], xydatar[i][2], xydatar[i][3], a3*32.4)


print ('E3 = ', E3, 'icount =', icount)
print(f"RMS = {E3 ** 0.5}")

last w01, w02, w03, w12, w23:
2.163511593467595 0.27235489623408915 0.5044057115886047 0.6902344554050847 0.6735185577892703
last b1, b2, b3:
-0.3847131460936745 -0.29623049181127603 -0.11764510376591081
20.0 13.0 310.8 30.97 36.26045150152061
20.0 14.5 308.0 32.3 36.686819428641414
20.0 15.3 306.0 31.5 36.89921797688958
20.2 13.0 310.8 30.91 36.647629179208764
20.0 14.5 308.0 32.5 36.686819428641414
20.0 15.3 306.0 31.4 36.89921797688958
24.0 13.0 310.8 35.59 44.00400505528346
36.0 14.5 308.0 46.4 67.66103364369278
E3 =  0.01873149248971602 icount = 8
RMS = 0.1368630428191483

In [14]:
predicted_values

[36.26045150152061,
 36.686819428641414,
 36.89921797688958,
 36.647629179208764,
 36.686819428641414,
 36.89921797688958,
 44.00400505528346,
 67.66103364369278]